<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-1CCS179" failures="1" tests="2" name="RegressionTest(failed)" time="38.105" errors="0" timestamp="2024-02-23T19:21:16 IST">
  <testcase classname="com.odoo.ap.testlayer.SignupTest" name="validate_sign_up_entering_all_valid_inputs" time="2.156">
    <failure type="java.lang.AssertionError" message="expected [https://ap-automation.odoo.com/my] but found [https://ap-automation.odoo.com/web/signup]">
      <![CDATA[java.lang.AssertionError: expected [https://ap-automation.odoo.com/my] but found [https://ap-automation.odoo.com/web/signup]
at com.odoo.ap.testlayer.SignupTest.validate_sign_up_entering_all_valid_inputs(SignupTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validate_sign_up_entering_all_valid_inputs -->
  <testcase classname="com.odoo.ap.testlayer.ProductTest" name="buyProductTest" time="25.525"/>
  <testcase classname="com.odoo.ap.testlayer.SignupTest" name="validate_sign_up_entering_invalid_inputs" time="0.0">
    <ignored/>
  </testcase> <!-- validate_sign_up_entering_invalid_inputs -->
</testsuite> <!-- RegressionTest(failed) -->
